services:
  stars-api:
    build: .
    container_name: stars-api
    env_file:
      - .env

    ports:
      - '8800:80'
    volumes:
      - ./:/code/
    restart: on-failure
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # depends_on:
    #   mysql_database:
    #     condition: service_healthy

  # mysql_database:
  #   image: mysql:8.3
  #   restart: unless-stopped
  #   command: --default-authentication-plugin=caching_sha2_password
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     MYSQL_USER: 'mysql'
  #     MYSQL_PASSWORD: 'mysql'
  #     MYSQL_ROOT_PASSWORD: 'mysql'
  #   ports:
  #     - '3307:3306'
  #   volumes:
  #     - mysql_database:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10

# volumes:
#   mysql_database:
#     name: mysql_database
