"""add discord role id to squad

Revision ID: 079a228ec6ed
Revises: df42d3b4b6a5
Create Date: 2026-02-02 14:52:00.940076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079a228ec6ed'
down_revision: Union[str, None] = 'df42d3b4b6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('discord_role_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad', 'discord_role_id')
    # ### end Alembic commands ###
