"""add_squad_model

Revision ID: 1a8b326c7c3d
Revises: b48a3d6f234e
Create Date: 2025-12-09 14:44:55.019816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a8b326c7c3d'
down_revision: Union[str, None] = 'b48a3d6f234e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('volunteer', 'email',
               existing_type=mysql.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'volunteer', 'squad', ['squad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.alter_column('volunteer', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=320),
               existing_nullable=True)
    op.alter_column('volunteer', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
