"""Change meeting_time to timezone aware

Revision ID: 36a7269cdf35
Revises: 60d8d5f3e218
Create Date: 2026-05-05 17:11:07.944908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a7269cdf35'
down_revision: Union[str, None] = '60d8d5f3e218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
