"""add github to volunteer

Revision ID: 42f35efc471b
Revises: 079a228ec6ed
Create Date: 2026-02-06 13:40:57.794524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f35efc471b'
down_revision: Union[str, None] = '079a228ec6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('github', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_volunteer_github'), 'volunteer', ['github'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_github'), table_name='volunteer')
    op.drop_column('volunteer', 'github')
    # ### end Alembic commands ###
