"""add volunteer status and history

Revision ID: 468e7b292839
Revises: 50fbad971fbc
Create Date: 2025-11-25 00:27:48.564919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '468e7b292839'
down_revision: Union[str, None] = '50fbad971fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_status_name'), 'volunteer_status', ['name'], unique=True)
    op.create_table('volunteer_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['volunteer_status.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('items', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.add_column('volunteer', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'volunteer', 'volunteer_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.drop_column('volunteer', 'status_id')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.alter_column('items', 'description',
               existing_type=sa.String(length=300),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_table('volunteer_status_history')
    op.drop_index(op.f('ix_volunteer_status_name'), table_name='volunteer_status')
    op.drop_table('volunteer_status')
    # ### end Alembic commands ###
