"""Add created_at to volunteer

Revision ID: 50fbad971fbc
Revises: 838af0da9402
Create Date: 2025-11-22 14:43:14.432521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50fbad971fbc'
down_revision: Union[str, None] = '838af0da9402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_items_description', table_name='items')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('volunteer', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('volunteer', 'linkedin',
               existing_type=mysql.VARCHAR(length=3000),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_volunteer_linkedin'), 'volunteer', ['linkedin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_linkedin'), table_name='volunteer')
    op.alter_column('volunteer', 'linkedin',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=3000),
               existing_nullable=True)
    op.drop_column('volunteer', 'created_at')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    # ### end Alembic commands ###
