"""add_discord_invite_sent_to_volunteer

Revision ID: 544f4a8a3a6f
Revises: 7cf65bf6bf3f
Create Date: 2026-01-06 00:00:09.701702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544f4a8a3a6f'
down_revision: Union[str, None] = '7cf65bf6bf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('discord_invite_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'discord_invite_sent')
    # ### end Alembic commands ###
