"""Add SquadAgenda model

Revision ID: 60d8d5f3e218
Revises: a879d6c0610f
Create Date: 2026-05-05 14:54:27.981618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d8d5f3e218'
down_revision: Union[str, None] = 'a879d6c0610f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
