"""Add volunteer types

Revision ID: 7cf65bf6bf3f
Revises: 03fa6dddb4dc
Create Date: 2025-12-14 17:50:57.474552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf65bf6bf3f'
down_revision: Union[str, None] = '03fa6dddb4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     'volunteer_type',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('name', sa.String(length=50), nullable=False),
    #     sa.Column('description', sa.String(length=255), nullable=True),
    #     sa.PrimaryKeyConstraint('id'),
    #     sa.UniqueConstraint('name')
    # )
    # op.create_index(op.f('ix_volunteer_type_name'), 'volunteer_type', ['name'], unique=True)

    op.bulk_insert(
        sa.Table(
            'volunteer_type',
            sa.MetaData(),
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('name', sa.String(length=50)),
            sa.Column('description', sa.String(length=255)),
        ),
        [
            {'id': 1, 'name': 'Junior', 'description': 'Volunteer with basic experience'},
            {'id': 2, 'name': 'Mentor', 'description': 'Experienced volunteer guiding others'},
            {'id': 3, 'name': 'Apoiador', 'description': 'Supporter volunteer'}
        ]
    )
    op.add_column('volunteer', sa.Column('volunteer_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'volunteer', 'volunteer_type', ['volunteer_type_id'], ['id'])
    
    # Update existing volunteers to default 'Junior' type
    op.execute("UPDATE volunteer SET volunteer_type_id = 1 WHERE volunteer_type_id IS NULL")
    
    # Make column not nullable
    # op.alter_column('volunteer', 'volunteer_type_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.drop_column('volunteer', 'volunteer_type_id')
    op.drop_index(op.f('ix_volunteer_type_name'), table_name='volunteer_type')
    op.drop_table('volunteer_type')
    # ### end Alembic commands ###
