"""add_discord_to_volunteer

Revision ID: 842ae7994682
Revises: 1a8b326c7c3d
Create Date: 2025-12-09 18:10:09.947931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842ae7994682'
down_revision: Union[str, None] = '1a8b326c7c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('discord', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'discord')
    # ### end Alembic commands ###
