"""add_is_apoiase_supporter

Revision ID: 8fb47fe0135f
Revises: 544f4a8a3a6f
Create Date: 2026-01-09 14:10:58.939692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb47fe0135f'
down_revision: Union[str, None] = '544f4a8a3a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('is_apoiase_supporter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'is_apoiase_supporter')
    # ### end Alembic commands ###
