"""Add initial volunteer statuses

Revision ID: 9c3cd5955758
Revises: 468e7b292839
Create Date: 2025-12-04 11:35:10.639603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c3cd5955758'
down_revision: Union[str, None] = '468e7b292839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "INSERT IGNORE INTO volunteer_status (name, description) VALUES "
        "('INTERESTED', 'Volunteer expressed interest.'), "
        "('CONTACTED', 'Volunteer has been contacted.'), "
        "('SCREENING', 'Volunteer is undergoing screening.'), "
        "('ACTIVE', 'Volunteer is active.'), "
        "('INACTIVE', 'Volunteer is inactive.')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM volunteer_status WHERE name IN ('INTERESTED', 'CONTACTED', 'SCREENING', 'ACTIVE', 'INACTIVE')")
    # ### end Alembic commands ###
