"""add description to squad

Revision ID: 9d6e1bd86f06
Revises: acafbc8a9999
Create Date: 2026-01-28 13:10:45.538298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6e1bd86f06'
down_revision: Union[str, None] = 'acafbc8a9999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad', 'description')
    # ### end Alembic commands ###
