"""add_referral_and_terms_fields_to_volunteer

Revision ID: a48937e1e488
Revises: 794a393796c0
Create Date: 2026-06-12 17:03:41.340921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48937e1e488'
down_revision: Union[str, None] = '794a393796c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('volunteer', sa.Column('referred_by_name', sa.String(length=255), nullable=True))
    op.add_column('volunteer', sa.Column('referred_by_position', sa.String(length=255), nullable=True))
    op.add_column('volunteer', sa.Column('referred_by_linkedin', sa.String(length=255), nullable=True))
    op.add_column('volunteer', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.add_column('volunteer', sa.Column('acceptance_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'acceptance_date')
    op.drop_column('volunteer', 'terms_accepted')
    op.drop_column('volunteer', 'referred_by_linkedin')
    op.drop_column('volunteer', 'referred_by_position')
    op.drop_column('volunteer', 'referred_by_name')
    op.drop_column('volunteer', 'bio')
    # ### end Alembic commands ###
