"""Add volunteer edit tracking

Revision ID: a74a653cbf11
Revises: 842ae7994682
Create Date: 2025-12-12 00:36:38.200336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74a653cbf11'
down_revision: Union[str, None] = '842ae7994682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('edit_token', sa.String(length=255), nullable=True))
    op.add_column('volunteer', sa.Column('edit_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('volunteer', sa.Column('daily_edits_count', sa.Integer(), nullable=True))
    op.add_column('volunteer', sa.Column('last_edit_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_volunteer_edit_token'), 'volunteer', ['edit_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_edit_token'), table_name='volunteer')
    op.drop_column('volunteer', 'last_edit_date')
    op.drop_column('volunteer', 'daily_edits_count')
    op.drop_column('volunteer', 'edit_token_expires_at')
    op.drop_column('volunteer', 'edit_token')
    # ### end Alembic commands ###
