"""add phone to volunteer

Revision ID: b48a3d6f234e
Revises: 9c3cd5955758
Create Date: 2025-12-08 13:52:34.259987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b48a3d6f234e'
down_revision: Union[str, None] = '9c3cd5955758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'phone')
    # ### end Alembic commands ###
