"""Add JobOpening and JobApplication

Revision ID: df42d3b4b6a5
Revises: 9d6e1bd86f06
Create Date: 2026-01-30 18:31:41.939893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df42d3b4b6a5'
down_revision: Union[str, None] = '9d6e1bd86f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
