"""Add mentor_mentee relationship

Revision ID: e9463ebe5b56
Revises: 885ee5c8b30c
Create Date: 2026-02-24 16:44:14.918570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9463ebe5b56'
down_revision: Union[str, None] = '885ee5c8b30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_mentee',
        sa.Column('mentor_id', sa.Integer(), nullable=False),
        sa.Column('mentee_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['mentee_id'], ['volunteer.id'], ),
        sa.ForeignKeyConstraint(['mentor_id'], ['volunteer.id'], ),
        sa.PrimaryKeyConstraint('mentor_id', 'mentee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor_mentee')
    # ### end Alembic commands ###
