"""add order to volunteer_type

Revision ID: fe37356bc2ec
Revises: f88261e5dc27
Create Date: 2026-02-15 14:09:34.674184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe37356bc2ec'
down_revision: Union[str, None] = 'f88261e5dc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_type', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_type', 'order')
    # ### end Alembic commands ###
