# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set Environment Variables for Testing
      run: |
        echo "PORT=8000" >> $GITHUB_ENV
        echo "DEBUG=1" >> $GITHUB_ENV
        echo "DB_DRIVER=mysql+mysqlconnector" >> $GITHUB_ENV
        echo "DB_USERNAME=mysql" >> $GITHUB_ENV
        echo "DB_PASSWORD=mysql" >> $GITHUB_ENV
        echo "DB_HOST=mysql_database" >> $GITHUB_ENV
        echo "DB_PORT=3306" >> $GITHUB_ENV
        echo "DB_DATABASE=db" >> $GITHUB_ENV
        echo "JWT_SECRETE_KEY=testestestestetsteste" >> $GITHUB_ENV
        echo "PASSWORD_HASH_ALGORITHM=HS256" >> $GITHUB_ENV
        echo "JWT_EXPIRE_MINUTES=30" >> $GITHUB_ENV

    - name: Test with pytest and coverage
      run: |
        pytest --cov=app --cov-report=term --cov-fail-under=100